### ISSUE TITLE
Can't seem to compile on macOS/Clang

### ISSUE THREAD

**Issue by IamRifki** [DerKoun/bsnes-hd#1]
I tried to compile this program on macOS, it seems to have some issues. Here's the output https://pastebin.com/raw/iyypKuCa

**Comment by DerKoun** [comment]
Thanks for reporting.
If you can enable any verbose settings please do so and post the complete log?
Also, can you compile the previous beta ( https://www.reddit.com/r/emulation/comments/bmc9t9/bsneshd_beta_5_bsnes_1073_formally_hd_mode_7_mod/ ) or vanilla bsnes 107r3 ( https://download.byuu.org/bsnes_v107r3-source.7z ) in the same environment? If so, a verbose log of these, to compare, may also help.

**Comment by IamRifki** [comment]
Here's the verbose output for [Beta 6](https://pastebin.com/P2dRnGQw). Here's BSNES [v107r3](https://pastebin.com/bDfP5yVt). Beta 5 is now broken on my machine for some reason, I guess this is a machine specific bug?

**Comment by Screwtapello** [comment]
[See this Reddit comment](https://www.reddit.com/r/emulation/comments/btcw7i/bsneshd_beta_6_bsnes_1073_formally_hd_mode_7_mod/ep3ig1r/)

**Comment by IamRifki** [comment]
Thanks Screwtapello, unfortunately it gives me this error now

`➜  bsnes git:(master) ✗ make
Compiling ../hiro/hiro.cpp ...
Compiling ../ruby/ruby.cpp ...
Compiling ../libco/libco.c ...
Compiling emulator/emulator.cpp ...
Compiling sfc/interface/interface.cpp ...
Compiling sfc/system/system.cpp ...
Compiling sfc/controller/controller.cpp ...
Compiling sfc/cartridge/cartridge.cpp ...
Compiling sfc/memory/memory.cpp ...
Compiling sfc/cpu/cpu.cpp ...
Compiling sfc/smp/smp.cpp ...
Compiling sfc/dsp/dsp.cpp ...
Compiling sfc/ppu/ppu.cpp ...
Compiling sfc/ppu-fast/ppu.cpp ...
In file included from sfc/ppu-fast/ppu.cpp:12:
sfc/ppu-fast/mode7hd.cpp:6:16: error: variable-sized object may not be
      initialized
  uint sampTmp[(256+2*ppufast.widescreen()) * 4 * scale/sampScale] = {};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [obj/sfc-ppu-fast.o] Error 1`

**Comment by DerKoun** [comment]
Thanks @Screwtapello, we got significantly further.
@IamRifki: Could you replace the offending line "mode7hd.cpp:6" (`uint sampTmp[(256+2*ppufast.widescreen()) * 4 * scale/sampScale] = {};`) with the following to see if it works?
`int sampSize = (256+2*ppufast.widescreen()) * 4 * scale/sampScale; 
uint *sampTmp = new uint[sampSize]; 
memory::fill<uint>(sampTmp, sampSize);`

**Comment by IamRifki** [comment]
It compiled. 
[bsnes-hd_beta6_macos.zip](https://github.com/DerKoun/bsnes-hd/files/3229804/bsnes-hd_beta6_macos.zip)

**Comment by DerKoun** [comment]
added the binary to the release, thanks
both fixes will be in the next beta

**Comment by DerKoun** [comment]
A quick macOS specific question:
In Settings/Drivers: What video and audio output options do you have?
thanks
