### ISSUE TITLE
Kirby's Dreamland 3 Transparency issues

### ISSUE THREAD

**Issue by KSSMarx** [DerKoun/bsnes-hd#10]
Issue: In Kirby's Dreamland 3 the water is not transparent, which makes the game... not very playable.
Version of emulator used : BSNES-HD Beta 9
![Water isn't transparent](https://user-images.githubusercontent.com/49493832/64521380-1a979000-d322-11e9-9b00-35ffdb5c0f1b.png)

**Comment by DerKoun** [comment]
Thanks. Could you provide a save state for the scene?

**Comment by KSSMarx** [comment]
> Thanks. Could you provide a save state for the scene?

Where are the save states located?

**Comment by DerKoun** [comment]
Same folder as the ROM, also same name, except for the extension

**Comment by KSSMarx** [comment]
[Kirby's Dream Land 3-2.zip](https://github.com/DerKoun/bsnes-hd/files/3590318/Kirby.s.Dream.Land.3-2.zip)

**Comment by DerKoun** [comment]
thank you. its on the todo list

**Comment by KSSMarx** [comment]
> thank you. its on the todo list

Thank you, too!

**Comment by DerKoun** [comment]
Didn't get to it before the release, sorry. Could you please verify it still happens in beta 10? And, if so, provide a new save state? I'll try to get it done this time.

**Comment by DerKoun** [comment]
fixed (in 2 steps)
