### ISSUE TITLE
Where does the chocolatey package install bsnes-hd to?

### ISSUE THREAD

**Issue by Toadfield** [DerKoun/bsnes-hd#101]
I installed [this package](https://community.chocolatey.org/packages/bsnes-hd/10.6) via the windows chocolatey package manager,but I can't find where it is located.

**Comment by DerKoun** [comment]
I didn't even know what chocolatey is. So I'll close this one as out of scope.
Also this is clearly a question. In such cases please use Discord instead of opening an issue that's not an issue.

**Comment by Toadfield** [comment]
sorry
