### ISSUE TITLE
Gamepad doesn't respond to any buttons

### ISSUE THREAD

**Issue by megapro17** [DerKoun/bsnes-hd#105]
If you open any game in bsnes core in Android, and minimize it, game will not respond to any buttons until app is restarted. This bug doesn't exist in other cores, e.g snes9x. It is in original bsnes too.

1. Open snes game in bsnes core
2. Connect gamepad or maybe keyboard will work too
3. Minimize and open RetroArch

**Comment by DerKoun** [comment]
I'm afraid I can't look into this in the near future, so I recommend reporting it for [bsnes](https://github.com/bsnes-emu/bsnes) and/or asking in the libretro Discord.
