### ISSUE TITLE
[Feature Request] Built-In NTSC/Blargg

### ISSUE THREAD

**Issue by InanimateCrbnRod** [DerKoun/bsnes-hd#107]
I hope this is the right place for this. I opened a similar request at the github for the regular bsnes libretro core in Aug with no response. I also don't know if this is the github for the libretro core or the regular version of bsnes-hd. I would like the option for the emulator itself to handle an ntsc filter the way genesis plus GX does. I get way cleaner multi-shader results in retroarch when the emulator handles ntsc output filters then when the pixel shaders do. I tried using retroarch's video filters but they are too demanding and they glitch out mode 7 graphics. Again sorry if this is the wrong place to ask

**Comment by DerKoun** [comment]
NTSC-filters don't work with the higher resolutions of bsnes-hd. So it's not a topic of interest for this fork.
In general I'd advice against going the non-shader route for significant performance reasons.
Most likely reporting the issues to RetroArch and/or the shader authors would be most useful.
