### ISSUE TITLE
Possible collaboration for hardware acceleration addition

### ISSUE THREAD

**Issue by noobynoob2** [DerKoun/bsnes-hd#108]
I'm new to Github so sorry if this isn't the appropriate place to post this, but I thought that you could possibly talk with Themaister [(his Github)](https://github.com/Themaister) to implement hardware acceleration for this project. He's the one that made the ParaLLEl for 64 emulation and he frequently commits to Mesa, so I'm pretty sure he'd be able to help you. I would ask him if he's able to but I couldn't find his e-mail :P

**Comment by DerKoun** [comment]
For suggestions that are not really features the best place the bsnes-hd Discord (see [readme](https://github.com/DerKoun/bsnes-hd#bsnes-hd-beta-106)).

I tend to not actively contact specific people directly asking for longer commitments to projects.
And after the release of parallel-rdp (one of his masterpieces IMO) I'd guess that Themaister gets quite a few such requests, which I imagine gets annoying quickly.
So please don't contact people directly. Doing some research and networking in chats or forums should be fine IMO.

The reason that I try to be very clear here is that there has been a case where a developer for other emulators actually felt harassed by a bsnes-hd fan.
I don't want anything like that to happen ever again.

I actually do have first volunteers for helping me with GPU based approaches. However, it will take some time until those projects can start. I currently have some other things to do before I can get back to coding as a hobby.
