### ISSUE TITLE
[Feature Request] Ares/Higan compatibility

### ISSUE THREAD

**Issue by CartoonFan** [DerKoun/bsnes-hd#111]
Hello there! I was wondering if your improvements work with the current higan or ares codebases? If not, would it be possible to port them over? I think it'd be great to have these amazing changes there! Thanks!

**Comment by DerKoun** [comment]
Higan (intentionally) misses the code that bsnes-hd modifies. Also it is intended to be hardware accurate, so these additions wouldn't fit it's purpose. 
For Ares there were talks some time ago which may be picked up again at some point. 
When I get back to actively working on bsnes-hd again I'll get back to talking to more people. So maybe some crossover will get going then.

**Comment by CartoonFan** [comment]
Awesome. Thanks!
