### ISSUE TITLE
[Feature Request] Version to PlayStation Vita

### ISSUE THREAD

**Issue by DavidinCT** [DerKoun/bsnes-hd#113]
Hi,

Is this possible to create a version that would work on the PlayStation Vita ? The Vita has 16:9 display and would be a perfect portable device to play 16:9 SNES games on. I got to play with this on the PC and Xbox One X and was blow away. 

Nothing ventured, nothing gained. 

Thanks !

**Comment by DerKoun** [comment]
duplicte: #84
