### ISSUE TITLE
Supersampling graphic issues on Contra III

### ISSUE THREAD

**Issue by Max833** [DerKoun/bsnes-hd#14]
https://github.com/byuu/bsnes/issues/156

**Comment by DerKoun** [comment]
It was closed by the reporter. Not sure what to do with that.

**Comment by MisaelK** [comment]
Oh hey, I was just going to open an issue with this same problem on the byuu's bsnes repo, but I guess this place is better. Contra 3 shows graphical errors when using HD Mode 7 with supersampling.

When raising the Mode 7 resolution from 240p to anything higher, nothing is wrong. But with supersampling enabled, some parts seem to shift to the left. The "Choose your starting point" text disappears, and part of the background shrinks and moves to the left.

https://streamable.com/xm7e7

Should I also post this in byuu's bsnes?

**Comment by DerKoun** [comment]
Does this happen in both bsnes and bsnes-hd, and, if so, does it look the same?

**Comment by MisaelK** [comment]
I just tested this on bsnes v110, v111r10 and bsnes-hd beta9. Only bsnes shows this problem.

The supersampling effect looks very different on bsnes and bsnes-hd, though. On bsnes it looks like downsampling, and on bsnes-hd it looks like antialiasing.

Will be creating an issue on bsnes soon, thanks!

**Comment by DerKoun** [comment]
The supersampling code is different, as bsnes-hd can combine it with scaling, while bsnes has it as an alternative . So it's possible certain issues only show up in one or the other.
