### ISSUE TITLE
add back libretro support

### ISSUE THREAD

**Issue by eadmaster** [DerKoun/bsnes-hd#15]
the current "bsnes" core on [RetroArch buildbot](https://buildbot.libretro.com/nightly/windows/x86_64/latest/) is based on [vanilla bsnes](https://github.com/byuu/bsnes) and it is missing [widescreen support and other cool features in this fork](https://github.com/byuu/bsnes/issues/108).

**Comment by DerKoun** [comment]
I'm working on merging the latest bsnes into my fork. When that is done I hope the creation of an additional core can be coordinated soon. Looking forward to that myself.

**Comment by FateForWindows** [comment]
> the current "bsnes" core on [RetroArch buildbot](https://buildbot.libretro.com/nightly/windows/x86_64/latest/) is based on [vanilla bsnes](https://github.com/byuu/bsnes) and it is missing [widescreen support and other cool features in this fork](https://github.com/byuu/bsnes/issues/108).

Necroposting here, but when the core was called bsnes-hd it was just a temporary name to distinguish it from the other bsnes cores, otherwise the Libretro core was just upstream bsnes without the widescreen or any other features from this fork besides HD Mode 7 despite them sharing the same name.

**Comment by eadmaster** [comment]
this can be closed as the libretro core is now available in retroarch. (thank you for taking some time for making this port)

**Comment by DerKoun** [comment]
Thanks for getting back to the issue and closing it. I would have waited another day or two to see if it works as expected. But if not that's a new issue anyway.
