### ISSUE TITLE
MSU-1 incompatible.

### ISSUE THREAD

**Issue by Sejha** [DerKoun/bsnes-hd#16]
All other versions of BSNES work with MSU-1 patches so, it feels awful to not have the feature and therefore to have to choose between the unique features of this version of BSNES, and not be able to take advantage of MSU functionality.

**Comment by DerKoun** [comment]
Could you describe the issue in more detail?
It's odd, because I haven't touched chip or audio code. It may resolve itself when I merge in the latest bsnes.

**Comment by Sejha** [comment]
It could be so, MSU-1 patches are based on code for a chip by byuu that allows snes games to play cd quality audio. All other cores of BSNES work with it, but this version ignores the instructions. So I figured that was due to an issue with the core itself.

**Comment by DerKoun** [comment]
Could you try the latest and oldest version from the release page here, each with clean configuration, to see if they have the same issue? Thanks

**Comment by Sejha** [comment]
Will do as soon as I have an opportunity.
    On Friday, October 18, 2019, 05:39:38 p.m. EDT, DerKoun <notifications@github.com> wrote:  
 
 
Could you try the latest and oldest version from the release page here, each with clean configuration, to see if they have the same issue? Thanks

**Comment by DerKoun** [comment]
Closing. If there are still (or again) MSU-1 issues, specific to bsnes-hd (standalone or libretro), please create a new issue.
