### ISSUE TITLE
No mode7 widescreen in Terranigma

### ISSUE THREAD

**Issue by bajolzas** [DerKoun/bsnes-hd#22]
the mode7 sections in Terranigma are not showing anything outside the normal area.
Some betas ago it did (dont remember wich).
all other section show the usual (a repeated screen).

Edit: tried Beta 6 and checking "ignore outside window" fixed it.
the same option on beta 10 doesnt seem to do anything.

**Comment by DerKoun** [comment]
Thanks for the detailed report. I can reproduce the regression and have a few guesses. I hope to have this fixed in the next release.

**Comment by DerKoun** [comment]
fixed
