### ISSUE TITLE
Gamma/Luminance/Saturation settings don't take effect

### ISSUE THREAD

**Issue by FitzRoyX** [DerKoun/bsnes-hd#23]
Just thought I'd report than any adjustments made to these sliders have no effect, even after restart. Output image is always default values.

Lum/Sat aren't useful, but byuu defaults to a dubious gamma setting, so it's worth making the gamma slider work at least.

**Comment by DerKoun** [comment]
Must have gotten lost when I merged true-color rendering. Will look into it.

**Comment by DerKoun** [comment]
fixed (with some tries)
