### ISSUE TITLE
Output window glitches out when focus is lost

### ISSUE THREAD

**Issue by FitzRoyX** [DerKoun/bsnes-hd#24]
![bsneshdg](https://user-images.githubusercontent.com/57089001/72317579-5ab7a800-365f-11ea-84d7-2b00d3fc2c6c.png)

**Comment by DerKoun** [comment]
Have that on my high priority list.

**Comment by DerKoun** [comment]
https://github.com/DerKoun/bsnes-hd/issues/12#issuecomment-574220285 might be a more serious effect of the same issue.

**Comment by DerKoun** [comment]
fixed (missed some places that require true-color changes)
