### ISSUE TITLE
Windowing uprezzing is broken

### ISSUE THREAD

**Issue by Electricstar** [DerKoun/bsnes-hd#25]
Title is self explanatory. HDMA uprezzing is bugged out. What I mean by that is, here's some example screenshots.

Super Mario Kart:
![image](https://user-images.githubusercontent.com/14850864/72366148-b3bb2680-36c7-11ea-8469-f3c448efa355.png)

Super Mario RPG (4x scale):
![image](https://user-images.githubusercontent.com/14850864/72366170-bf0e5200-36c7-11ea-836f-7eedb93ee266.png)

Super Mario RPG (1x scale):
![image](https://user-images.githubusercontent.com/14850864/72366196-c6cdf680-36c7-11ea-9776-b2b562ddc291.png)

**Comment by DerKoun** [comment]
Guess something went wrong in the big merge with latest bsnes. Will have to track that down.
The scale comparison is especially helpful, thanks. Somewhere the scale seems to be missing, offsetting values upwards,

**Comment by DerKoun** [comment]
fixed (note: this feature is still experimental)
