### ISSUE TITLE
No shaders except 'blur' showing up, Filters not showing up at all

### ISSUE THREAD

**Issue by Electricstar** [DerKoun/bsnes-hd#26]
Latest BSNES-hd doesn't seem to work with main BSNES' shaders except blur, and doesn't have filters at all. The shaders are indeed in the 'shaders' folder, as well.
![image](https://user-images.githubusercontent.com/14850864/72366357-1d3b3500-36c8-11ea-8a64-86589350ec71.png)

**Comment by DerKoun** [comment]
I have intentionally removed the filters from the menu. They don't work with the true color rendering.
The shaders are displayed for me, but only when I choose OpenGL as driver. IIRC that is normal.

**Comment by bajolzas** [comment]
yeah, shaders only work OpenGL. 
Also is there any reason to use a filter instead of any of the available shaders?

**Comment by Electricstar** [comment]
> Yeah, shaders only work with OpenGL.
> Also is there any reason to use a filter instead of any of the available shaders?

Why wouldn't you use filters? They can be used in combination with shaders.
I use NTSC (RF) filter in combination with NTSC Shader.

**Comment by DerKoun** [comment]
So, do the shaders show up for you when using OpenGL?
And If so, can this issue be closed?

**Comment by Electricstar** [comment]
Shaders do indeed show up when using OpenGL. This can be closed.

**Comment by DerKoun** [comment]
thanks
