### ISSUE TITLE
Resolutions are incorrect; were correct in beta-9

### ISSUE THREAD

**Issue by Knucklesfan** [DerKoun/bsnes-hd#29]
Hi. Today I recently upgraded to beta-10, and I really enjoy the new features. Sadly, it has one massive bug which seriously affects most monitors/games. In previous builds of bsnes-hd, when set to 16:9, the resolution was set to 400x224. however, now, bsnes-hd runs at 384x224, which cuts off a serious amount of screen resolution. Also, without enabling overscan, the picture cuts off the first few pixels from the top of the image, which can hurt some games. Enabling overscan causes the black bars as seen here, and is quite annoying. None of these issues were present in the classic bsnes-hd. The following screenshots were taken using print-screen on 2 1080p monitors, running in the 16:9 aspect ratio.
![weirdresolutions1](https://user-images.githubusercontent.com/17733165/72488698-5a421d00-37d7-11ea-9843-847993aadf7f.png)
On the right is bsnes-hd beta 10 while on the left is bsnes-hd beta 9, the difference is pretty obvious. I haven't tested on the libretro core yet, but I'd assume the same bugs are present.
None of these bugs are seen in regular bsnes, which leads me to believe its a problem either A: on my end, or B: on the emulator's end. Either way, hope this helps.
 I hope this helped you fix your wonderful emulator.

**Comment by DerKoun** [comment]
Some of those things are intentional, but work-in-progress. There may also a bug or 2 in there, but spontaneously I don't see any. I'll update this issue when I look into it.

For the black bars: Disable both Show Overscan and Aspect Correction. Then (at 16:9) you get exactly a 5th of 1080p, so it will scale perfectly.

**Comment by Knucklesfan** [comment]
> Some of those things are intentional, but work-in-progress. There may also a bug or 2 in there, but spontaneously I don't see any. I'll update this issue when I look into it.
> 
> For the black bars: Disable both Show Overscan and Aspect Correction. Then (at 16:9) you get exactly a 5th of 1080p, so it will scale perfectly.

If I disable overscan, the top few line of pixels are cut off, is that intentional?

**Comment by DerKoun** [comment]
Yes, see: https://github.com/DerKoun/bsnes-hd/blob/master/README.md#user-content-differences-in-settingoptions-from-bsnes
Correct widescreen aspect ratios for every combination of overscan and aspect correct settings is planned. That is a work-in-progress ATM.

**Comment by DerKoun** [comment]
Widescreen AR is now applied based on the related settings.
Also you can specify the additional pixel columns directly using setting override files.
