### ISSUE TITLE
Wrong Colors

### ISSUE THREAD

**Issue by bajolzas** [DerKoun/bsnes-hd#31]
Beta 10.2 seems to have the color adjustment wrong
here is how it looks
![bhdb10 2](https://user-images.githubusercontent.com/51722671/73611890-ae723d00-45de-11ea-9ca1-bacbc795c735.png)

here is how it looks on bsnes 114.3
![b114 3](https://user-images.githubusercontent.com/51722671/73611895-c8138480-45de-11ea-8a16-50e016d5fb99.png)

Both are using 100% luminance, 100% saturation and 150% gamma.
My guess is something is wrong with with the gamma setting as at 100% they seem pretty close if not the same.

**Comment by DerKoun** [comment]
fixed multiple related issues (over multiple releases) and changed gamma default to 100.
