### ISSUE TITLE
 Add RetroAchievements support

### ISSUE THREAD

**Issue by nfp0** [DerKoun/bsnes-hd#36]
Almost all bsnes and higan cores in Retroarch support RetroAchievements (even higan Accuracy and nSide Balanced, contrary to the info in the docs).

It would be great to have this excellent core also supporting RetroAchievements. Maybe code from the other bsnes/higan cores can be ported to this one to save time.

According to a contributor on the upstream repository, the missing implementation is this:
https://github.com/DerKoun/bsnes-hd/blob/87173e8ec8625ee041aa93ce98130029ef6eac43/bsnes/target-libretro/libretro.cpp#L1004-L1014

Byuu says he won't do it himself but he'll be happy to accept a pull request if anyone implements this.
Is this a tall order, considering all previous higan/bsnes cores already implemented this?

I've also opened this issue here https://github.com/libretro/bsnes/issues/27 on the libretro vanilla bsnes repository.

**Comment by DerKoun** [comment]
I have to defer this to libretro. Memory is a part of the emulator I have no idea about. So I'll close this as out of scope, as it is not a video feature. Sorry.

**Comment by nfp0** [comment]
Sure. It's understandable.
