### ISSUE TITLE
10.3 beta no executable flag on mac

### ISSUE THREAD

**Issue by ambyra** [DerKoun/bsnes-hd#37]
I had to open the app and chmod 755.

**Comment by DerKoun** [comment]
OK, I'll need some help here. Please consider me a Windows guy with no access to a Mac and little to no experience with building C++ Application, especially for Mac or Linux. (It's not entirely that bad, but please consider me dumb in this issue just to be safe.) 
So 2 questions on using 'chmod' to make the app executable, so I can try to add it to the build:
1) Is this flag kept when I zip the app?
2) What target do I have to chmod ("bsnes_hd.app", "bsnes_hd.app/Contents/MacOS/bsnes" or something else)? Maybe post the command line to be sure I get it right ...

**Comment by DerKoun** [comment]
So it seems the command should look like this:

`chmod +x bsnes_hd.app/Contents/MacOS/bsnes`

And I should replace ZIP with TAR to keep the permission:

`tar -jcvfp archive.tar.bz2 folder`

I guess the same changes could be made for the Linus builds

**Comment by DerKoun** [comment]
Please see https://github.com/DerKoun/bsnes-hd/issues/11#issuecomment-596469072 for test builds. Feedback is appreaciated.

**Comment by DerKoun** [comment]
fixed in new beta 10.4
Mac and Linux builds are now tar.bz2 to keep the executable flag.
@ambyra please confirm
