### ISSUE TITLE
Linux build for Beta 7 (download, not request)

### ISSUE THREAD

**Issue by 143mailliw** [DerKoun/bsnes-hd#4]
[bsnes.zip](https://github.com/DerKoun/bsnes-hd/files/3317638/bsnes.zip)
It's just one file, but GitHub doesn't like "bsnes" files

**Comment by 143mailliw** [comment]
Not that neither audio nor the speed regulator work.

**Comment by 143mailliw** [comment]
accidentally closed

**Comment by DerKoun** [comment]
Thank you, added it to the release downloads with your note.

About the issues: I don't know how you built it. For Windows I used the guide from the following site:
https://higan.readthedocs.io/en/stable/install/linux/
Maybe the Linux guide will help you. For current bsnes skip the Icarus steps and replace 'higan' with 'bsnes' where appropriate. Maybe it's just missing dependencies.

**Comment by 143mailliw** [comment]
I'm not missing the audio dependencies, I know I'm not because I had to install them, and the beta 5 build had the same problems.

**Comment by 143mailliw** [comment]
I did make in the bsnes folder, was I not supposed to?

**Comment by 143mailliw** [comment]
Changing the audio driver to "PulseAudio Simple" fixes both issues, should be noted in the release note or default configuration file changed (see settings.bml -> ```Audio
  Driver: PulseAudio Simple```)

**Comment by DerKoun** [comment]
Updated changelog and Reddit post and will look into it in more detail later, thanks
It's not directly related to this issue, but would be helpful for future improvements: Could you list the video and audio 'driver' options do you have in "Settings/Drivers" on Linux?

**Comment by 143mailliw** [comment]
Sure, this issue happens on vanilla bsnes FYI.

**Comment by 143mailliw** [comment]
Video:
- OpenGL 3.2
- XVideo
- XShm
- None

Audio:
- ALSA (default, doesn't work, breaks frame limiter, interfacing with ALSA direct is a _bad_ idea when PulseAudio is running (can crash Pulse) and should not be done)
- OSS (doesn't work)
- OpenAL (non functional at all, just errors out)
- PulseAudio (stutters, causes lag)
- PulseAudio Simple (works well)
- libao (again, just errors out)
- None

Input:
- udev (best option, default, lowest input latency)
- SDL
- Xlib
- None

**Comment by DerKoun** [comment]
thanks

**Comment by eadmaster** [comment]
please statically link your linux builds or use Flatpak, i am getting library errors running the builds in the release section on my Ubuntu Bionic setup:
`bsnes: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bsnes)`

**Comment by DerKoun** [comment]
@eadmaster please try the following CI test build: [bsnes-hd_linux-test.zip](https://github.com/DerKoun/bsnes-hd/files/3356745/bsnes-hd_linux-test.zip)
Would be good to know if it works and/or if you have any suggestions, thanks.

**Comment by eadmaster** [comment]
thank you that version is loading fine, but it has some rendering bugs, so i am staying with [this older build for the moment](https://gitlab.com/higan/higan/-/jobs/artifacts/bsnes-hd/download?job=bsnes-linux-x86_64-binaries).

**Comment by DerKoun** [comment]
Thanks for testing. Could you add a description and/or, even better, a screenshot of the rendering issue? I would like to look into it.

**Comment by eadmaster** [comment]
sorry for the late reply, here it is an example of the rendering issues i've mentioned:
![Uchuu Race - Astro Go! Go! (J)  t eadmaster -001](https://user-images.githubusercontent.com/925171/60880930-ee3d9580-a244-11e9-91fd-0ed5be529b58.png)

my current settings:
![Screenshot_20190709_122930](https://user-images.githubusercontent.com/925171/60881086-42487a00-a245-11e9-8852-fd84636c2d9f.png)

**Comment by eadmaster** [comment]
UPDATE: fixed by `cp *.bml $HOME/.local/share/bsnes/`
