### ISSUE TITLE
Possible to compile for macOS 10.14.x and Up on the official releases?

### ISSUE THREAD

**Issue by rbreaves** [DerKoun/bsnes-hd#40]
The binaries only appear to run on 10.15.+.

**Comment by DerKoun** [comment]
Please try the test builds from https://github.com/DerKoun/bsnes-hd/issues/11#issuecomment-596469072 and comment in that issue if they don't work as expected, thanks.

**Comment by DerKoun** [comment]
Changed in new beta 10.4
@rbreaves please confirm
