### ISSUE TITLE
Standalone mac app doesn't run

### ISSUE THREAD

**Issue by quinton-ashley** [DerKoun/bsnes-hd#41]
Error says can't be opened.  The app is not executable.  This isn't caused by an unidentified developer warning either.

**Comment by DerKoun** [comment]
Please try the test builds from https://github.com/DerKoun/bsnes-hd/issues/11#issuecomment-596469072 and comment in that issue if they don't work as expected, thanks.

**Comment by DerKoun** [comment]
fixed in new beta 10.4
Mac and Linux builds are now tar.bz2 to keep the executable flag.
@quinton-ashley please confirm

**Comment by quinton-ashley** [comment]
works!
