### ISSUE TITLE
bsnes-hd 10_3 "forgets" how to do widescreen after I close the app.

### ISSUE THREAD

**Issue by superluigi018** [DerKoun/bsnes-hd#45]
When I first downloaded bsnes-hd, the widescreen function was fully functional. Then when I close the app and reopen it, even though my settings appear to be the same, the widescreen function is completely nonfunctional. The games are stuck in 4:3. I have to set up the entire emulator in an entirely new folder to get it working again. And as soon as it closes, widescreen stops working again. I have also noticed that when I relaunch it, my settings.bml file is edited. Even when I replace the edited file with the original, functional file, widescreen still doesn't work. I have to keep transferring my game files and save files again and again and keep reinstalling bsnes-hd.

**Comment by DerKoun** [comment]
Sorry for the late reply. I'm currently sorting out some things and plan to return to working on bsnes-hd soon(tm).
The issue seems quite unique, so it will be hard reproduce. I have some further questions that might help:
Are you using the latest version? Have you tried earlier ones?
What is the environment, operating system incl. version, hardware and so on? (I assume it's not the libretro core)
By "nonfunctional" you mean black bars on both sides in full screen and the window being in 4:3 ratio?
Do you actually have to move the ROMs and save-states to a different folder to (temporarily) fix it?
Sorry I can't be more help. I have not experienced or heard of this specific issues, yet.

**Comment by SaraJLeen** [comment]
I've had an issue like this as well; it seems like certain widescreen-related settings simply do not seem to take correct effect on launch and have to be toggled to take effect. Quite irritating, really! Sometimes making overrides for specific files seems to help, but even then, those don't seem to work 100% correctly either unless the rom is in a zip file. x_x

**Comment by superluigi018** [comment]
I am using bsnes-hd version 10.3 on Windows 10 Home 1909. I used to think that the only way to fix it was to reinstall every time I used it. I later realised that I can go into enhancements and change widescreen "all" to "none" and back to "all". It seems that when I close the program the settings for widescreen are written from on to off but the program doesn't know that so I have to fix it myself. It's nothing I lose sleep over, just a minor annoyance.

**Comment by DerKoun** [comment]
Thanks for the confirmation and the update. I now have an idea where to look.
To be honest, adding settings to bsnes is not easy for me. I have had more than one bug that was in that part of the code, not the actual graphics output code.
To be sure, it is only this one setting that 'secretly' resets?

**Comment by SaraJLeen** [comment]
I've noticed it with the ignore/auto/all window setting and probably a couple of other widescreen settings, along with the main widescreen off/mode7/all setting. It might happen with all of the widescreen settings, for all I know personally.

**Comment by DerKoun** [comment]
OK, I'll try to find the issue for the next version.
A workaround you can try is using retroarch (or another libretro frontend). Depending on where in the settings it goes wrong only the standalone version would be affected.

**Comment by VitorVilela7** [comment]
Basically the settings file only seem to affect the UI, while the emulator core itself loads with the default widescreen values. "Reloading" the UI values manually by hand takes the effects on the emulator core.

In other words:
1. settings file is applied over UI
2. however when setting file is applied over UI, the UI doesn't reflect the changes to the emulator core

Likely fix is:
1. apply settings file on both UI and emulator core by hand; or
2. ensure the UI "changes" reflects on the emulator core even if the values are changed during initialization.

I'm on Windows 10 as well.

**Comment by DerKoun** [comment]
fixed in new beta 10.4
Settings (as well as setting overrides) are now loaded and applied properly
@superluigi018 & @SaraJLeen please try it out
