### ISSUE TITLE
Super Castlevania IV - ectoplasms are invisible

### ISSUE THREAD

**Issue by Arthandas** [DerKoun/bsnes-hd#47]
I'm using the latest Bsnes HD RetroArch core and the Japanese SCIV rom from the Anniversary Collection. The ectoplasms in Stage 6 are invisible and whenever they attack there's a large colorful beam across the whole screen.
I can supply a save state near the ectoplasms if needed.
![Akumajou Dracula (Japan) (Castlevania Anniversary Collection)-200728-184912](https://user-images.githubusercontent.com/41027064/88696376-7833f700-d103-11ea-8aa2-487eb1182c44.png)

**Comment by DerKoun** [comment]
Could you try setting `WideScreen Ignore Window` to `none` and `HD Windowing` to `0` to see if this fixes the issue? If so, could you also try which values on these two settings break this effect and which don't? Thanks

**Comment by Arthandas** [comment]
Thanks for the quick reply!

Setting WideScreen Ignore Window to none completely fixes the issue, all other options break it.
HD Windowing has no effect and it was set to 0 by default (I checked the other values too).

I'm playing with widescreen turned off (WideScreen Mode none) so it's a little weird that it still manages to break something.

**Comment by DerKoun** [comment]
Good to hear. It is intended to affect the non-widescreen area as well. Maybe naming isn't optimal there. Also it maybe be worth investigating if I can automate it more, e.g. to not affect transparent effects.

**Comment by DerKoun** [comment]
@Arthandas could you still provide me a save state? I'd like to try to make the default more automatic, so it avoids black borders but does not break effects such as this one. And I need an example to check against. thx

**Comment by Arthandas** [comment]
Sure, I'll upload it later today.

**Comment by Arthandas** [comment]
Here it is, just go left.
[Akumajou Dracula (Japan) (Castlevania Anniversary Collection).zip](https://github.com/DerKoun/bsnes-hd/files/5011936/Akumajou.Dracula.Japan.Castlevania.Anniversary.Collection.zip)

**Comment by DerKoun** [comment]
Thanks
