### ISSUE TITLE
Widescreen is always enforced

### ISSUE THREAD

**Issue by KawaiiWafu** [DerKoun/bsnes-hd#53]
I prefer playing the games in 4:3 resolutions, but I like the smoother look of the games, so I always disable the widescreen functionality, but I have to do it every single time, because although it remembers the option, the game is still in widescreen. I have to re-pick 4:3 in the enhancements even though it's set to it. All games do this.

**Comment by DerKoun** [comment]
This is a known issue affecting multiple settings. Will be solved in the next beta.

**Comment by wojpawlik** [comment]
Workaround: [override files](https://github.com/DerKoun/bsnes-hd#setting-override-files). Duplicate of #45.

**Comment by DerKoun** [comment]
fixed in new beta 10.4
Settings (as well as setting overrides) are now loaded and applied properly
@KawaiiWafu please try it out
