### ISSUE TITLE
HD windowing option not working on libretro

### ISSUE THREAD

**Issue by dxgldotorg** [DerKoun/bsnes-hd#55]
Using bsnes-hd-beta core in libretro, every option works except the experimental HD Windowing feature.  On both Windows x64 and Android AARCH64 the windowing stays at native resolution.

**Comment by DerKoun** [comment]
Yes, that setting has a typo in its code (haven't tested, yet, but that should be it),
Should be fixed in the next beta (no ETA on that, sorry)

**Comment by DerKoun** [comment]
Fixed in beta 10.4
@dxgldotorg please verify

**Comment by dxgldotorg** [comment]
As a heads-up, it works fine now.
