### ISSUE TITLE
won't run on Catalina

### ISSUE THREAD

**Issue by asheenlevrai** [DerKoun/bsnes-hd#62]
Hi :)
First of all I'm very new to this so I probably missed something very obvious. Sorry if that's the case. I'll happily use the education you might provide :)

I DLed the current release for macOS (Beta 10.3) and tried to launch it on Catalina (10.15.7).
However it won't launch ("the application can't be opened"). It's not like sometimes when it says it's from an unknown developer and I need to right-click and select open. I didn't find any way around it here.
thank you very much in advance for your help.

(I could run the latest nightly of the "regular" bsnes for mac alright if that means anything)
Best,
-a-

**Comment by DerKoun** [comment]
Could you please try the Mac test build from: https://github.com/DerKoun/bsnes-hd/issues/11#issuecomment-596469072
Would be good to know if that fixes it, or at least makes any difference.

**Comment by asheenlevrai** [comment]
Yes it works )
Thanks
