### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Infinality** [DerKoun/bsnes-hd#64]
I haven't seen much of anything in 9 months, on github or reddit.  Is this project still active?

**Comment by DerKoun** [comment]
_Technically this is not an issue and should rather be asked on Discord. But having the answer archived here may also help people find it, so:_

**I have not abandoned this project.**
I keep an eye on it, answering issues here and chatting on Discord. However I currently don't have the time and mental shape to get back into actual coding. I really do want to, but not before I'm sure that can actually finish a bugfix release and get to working on the planned optimizations.
So, feel free to post issues and join the Discord for support or discussions. But for now please don't expect a release date for the next beta.

**Comment by Infinality** [comment]
Sorry for the noise, I was just curious.  Is there any plan to add the widescreen support upstream in bsnes?

**Comment by pleasejustgo** [comment]
Hope and pray for you DerKoun. This project is incredible. You're doing a great service to the emulation community. Get better soon.

**Comment by DerKoun** [comment]
> Sorry for the noise, I was just curious. Is there any plan to add the widescreen support upstream in bsnes?

Don't worry about it. It's a legitimate question.
Currently, no. AFAIK that hasn't changed when the project hanged hands. Without more ROM patches this feature will likely stay exclusive to forks.

> Hope and pray for you DerKoun. This project is incredible. You're doing a great service to the emulation community. Get better soon.

Thanks so much. I'm not religious, but knowing someone actually prays for me feels really good.

**Comment by Quest79** [comment]
May your days be better, DerKoun!

I found my way here becuse RA doesnt have this on their core list. People say that bsnes was merged or something but that doesnt do any good when all kinds of features are gone in the 'official' version. Strange!

**Comment by DerKoun** [comment]
After 2 releases I feel confident I can close this issue.
But let me say again that your kind words mean the world to me. Thank you, all of you.
