### ISSUE TITLE
Feature Request: Game Specific Options

### ISSUE THREAD

**Issue by teconmoon** [DerKoun/bsnes-hd#7]
As we know when it comes to weird graphics settings, not all games are equal. This request is for bsnes-hd to be able to remember specific settings for specific games.

For example, GLideN64 can remember game-specific settings so that I could enable a graphic setting for one specific game without affecting others. This is essentially what I am requesting.

Please let me know if this needs clarification, or if this is already planned, or is out of scope for bsnes-hd and will never happen. Thanks for reading!

**Comment by DerKoun** [comment]
I'll put this on the list of things for which I look for volunteers. Someone with more C++ experience should be able to add this much easier than me.
Maybe I'll put together a simple external tool to launch games with their own settings being copied in and out before and after

**Comment by DeathWrench** [comment]
I ended up making some batch files that do this, though it might not be as convenient. It is a temporary solution.

* First I made a folder called presets in the root directory of bsnes.
![https://cdn.discordapp.com/attachments/515842332201975821/624077283656990720/unknown.png](https://cdn.discordapp.com/attachments/515842332201975821/624077283656990720/unknown.png)
* Then I made two folders in presets called alttp and metroid
![https://cdn.discordapp.com/attachments/515842332201975821/624077444357554186/unknown.png](https://cdn.discordapp.com/attachments/515842332201975821/624077444357554186/unknown.png)
* I configured the settings for A Link to the Past and copied configuration.bml into the alttp
* Do the same for Super Metroid and copy the configuration.bml into the metroid folder
* I then made 2 .bat files in the root directory
#### alttp.bat
`xcopy /u /y %~dp1presets\alttp\configuration.bml "%~dp0"`
#### metroid.bat
`xcopy /u /y %~dp1presets\metroid\configuration.bml "%~dp0"`
![https://cdn.discordapp.com/attachments/515842332201975821/624079430586728450/unknown.png](https://cdn.discordapp.com/attachments/515842332201975821/624079430586728450/unknown.png)
Hopefully this helps

**Comment by DerKoun** [comment]
Added a simple version, see readme. I'll expand it in the next releases.
