### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by MapleStoryPSN** [DerKoun/bsnes-hd#70]
Tested on both the current bsnes-hd beta retroarch core and standalone emulator. Launch any game and monitor ram usage. It will gradually climb at a rate of roughly 1mb a second, even if left completely idle in game on a static screen. No other SNES cores, base bsnes included, exhibit this behavior.

**Comment by DerKoun** [comment]
Great find, thank you.
That is what happens when a Java developer wades through the circle of hell that is C++. He doesn't deallocate his arrays.
There were two happening every frame(!!) and one when you change Color Adjustments. And all together were literarily fixed with 3 lines of code.

**Comment by DerKoun** [comment]
This fix is now live for the libretro core. That also fixes breaking flickering on the Switch.

**Comment by DerKoun** [comment]
Fixed in the new beta 10.4
@MapleStoryPSN If you have time to verify I'd appreciate it.
