### ISSUE TITLE
128kb+ VRAM

### ISSUE THREAD

**Issue by snaphat** [DerKoun/bsnes-hd#77]
Does the HD version of bsnes support expanded VRAM (I see the option for 128kb and 256kb expansion in bsnes-plus)?

Background: I am working on widescreen modifications for FF3/6 which uses 256x256 buffers for BG1, BG2, and BG3 layers.  So I've expanded the layers to 512x256 using what I thought to be unused portions of VRAM.  It turns out that under certain circumstances (opening doors in towns, etc.)  those areas of VRAM are loaded with a modified version of tile data with the new "open door" tile loaded and the pointers for the layers swapped to the new areas of vram. It is basically a back buffering scheme where the pointers for the front and back buffers are swapped. Currently, I'm not sure it is necessary, I don't why they are doing this vs just updating the original buffer. But, it seems that if those areas are necessary, there's not enough unused VRAM left for the expanded 512x256 BG layers.

**Comment by DerKoun** [comment]
I can't personally help you with the VRAM expansion, but I'm asking around and will get back to you.
Regarding the widescreen-hack: That's great. Please join our discord. We have a dedicated widescreen-hacks channel.
https://discord.gg/zXsZ78n7

**Comment by DerKoun** [comment]
Extended VRAM is not available, yet. But planned for a future release.

**Comment by DerKoun** [comment]
It's available now via a setting override. Anyone interest in using it for ROM hacks (widescreen or otherwise) please join our Discord.
