### ISSUE TITLE
Bug: FF6 sprites appear in front of a background later that should cover them

### ISSUE THREAD

**Issue by snaphat** [DerKoun/bsnes-hd#79]
There appears to be a z-order issue with no sprite limit enabled. Initially, I thought this was an FF6 widescreen bug, but after testing I found it also happens on the vanilla game and occurs specifically if no sprite limit is enabled. Pictures below:

With No sprite limit unchecked (and game reload):
![image](https://user-images.githubusercontent.com/5836001/115945756-14b8d900-a48b-11eb-9129-9fe354192df9.png)

With No sprite limit checked (and game reload): 
![image](https://user-images.githubusercontent.com/5836001/115945779-2dc18a00-a48b-11eb-9c2a-1dbec9fd8a14.png)

**Comment by DerKoun** [comment]
Thanks for the detailed report. As 'no sprite limit' is not an HD feature I have to ask: Does this also occur in bsnes (latest and/or 114.3)?

**Comment by snaphat** [comment]
Good observation, I will check. My guess is yes it does occur on the regular bsnes then. It also occurs to me that I know those bottom menu layers are drawn using a horizontal synchronized buffer swap (so specific timing required) and I have suspicion it's somehow related to that

**Comment by snaphat** [comment]
For 114.3, do you mean bsnes-hd beta 4, or do you mean bsnes 114.3? If the latter, where is a copy of that?

**Comment by snaphat** [comment]
Same issue occurs on vanilla Bsnes v115

**Comment by Max833** [comment]
> Same issue occurs on vanilla Bsnes v115 and master

I mean... what do you expect? This feature is not a hardware accurate behaviour. There are always problems when no sprite limit is checked. In every emulator out there. ^^;

**Comment by snaphat** [comment]
> > Same issue occurs on vanilla Bsnes v115 and master
> 
> I mean... what do you expect? This feature is not a hardware accurate behaviour. There are always problems when no sprite limit is checked. In every emulator out there. ^^;

I just thought it was related to -HD, but looks like it's not

**Comment by DerKoun** [comment]
If it is a bug (I don't know if it is), the best place to have a go at it would be [the bsnes issue tracker](https://github.com/bsnes-emu/bsnes/issues?q=sort%3Aupdated-desc). I appreciate the report anyway.
