### ISSUE TITLE
unable to install bsneshd on Linux

### ISSUE THREAD

**Issue by antaresu90** [DerKoun/bsnes-hd#80]
How do you install bsneshd on Llinux? I extracted the file, but it does not come with instructions.

**Comment by DerKoun** [comment]
Just run the executable "bsnes_hd" form the root of the archive.

**Comment by antaresu90** [comment]
> Just run the executable "bsnes_hd" form the root of the archive.

How do I do that? Sorry I'm not familiar with linux, I just started to use it.

**Comment by DerKoun** [comment]
Try "./bsnes_hd" when in the folder. If that doesn't help I have to ask you to try a Linux beginners forum or Discord. Also I'll close this for not being a bsnes-hd bug or feature request.
