### ISSUE TITLE
Doesn't use my theme

### ISSUE THREAD

**Issue by Toadfield** [DerKoun/bsnes-hd#81]
I am on arch kde and for some reason it doesn't use my theme
![image](https://user-images.githubusercontent.com/68649672/119409154-2807d000-bce7-11eb-8e73-b8d96cdf2254.png)

**Comment by DerKoun** [comment]
Does this also happen in the latest bsnes?

**Comment by Toadfield** [comment]
yes

**Comment by DerKoun** [comment]
If it's not HD-specific please report it over there. I can likely merge the change. If not, it'll come in when I sync with bsnes the next time.
