### ISSUE TITLE
[Feature Request] Netplay support

### ISSUE THREAD

**Issue by Toadfield** [DerKoun/bsnes-hd#82]
it would be fucking cool to be able to play snes games with hd mode 7 and widescreen online.
I know I can use something like persec,but I don't have money and it would be cool to be able to create lobbys and stuff like that.

**Comment by DerKoun** [comment]
Please report non-HD issues to the bsnes project. I doubt I'd work on anything like this output. I wouldn't know how.
If bsnes-hd has issues bsnes does not, please let me know.
