### ISSUE TITLE
Ps Vita Version

### ISSUE THREAD

**Issue by julioapc16** [DerKoun/bsnes-hd#84]
Hello Friend you can release a version for Ps Vita, The Vita community thanks you.

**Comment by DerKoun** [comment]
From what I read the Vita can bare handle normal SNES emulation. The accuracy of bsnes and video features of bsnes-hd seem much too demanding for the hardware. Please correct me if I'm wrong.

**Comment by julioapc16** [comment]
It's wrong Friend, the vita emulator versions are old, need to be updated or launch new emulators, we don't even have support for msu-1.

**Comment by julioapc16** [comment]
You can launch a basic version with support for msu1, we do not have any emulator with support for CD quality sound in Vita.

**Comment by DerKoun** [comment]
I asked around and it seems the Vita actually couldn't handle bsnes(-hd). So I won't put time into it or ask anyone to do so.
However, if anyone gets the core to build for the Vita and wants to do some benchmarks, let me know. I'll gladly help validating what the Vita can or can't do.
