### ISSUE TITLE
Error when launching on Manjaro Linux

### ISSUE THREAD

**Issue by armoar334** [DerKoun/bsnes-hd#85]
when running ./bsnes_hd (standalone, linux)I get this error:
./bsnes_hd: error while loading shared libraries: libgtksourceview-2.0.so.0: cannot open shared object file: No such file or directory
I have gtk3, gtk2, lib32-gtk2 and lib32-gtk3 installed so i cannot think of nor find anything that would cause this error.

**Comment by DerKoun** [comment]
It seems libgtksourceview is required for some legacy reason. For now you will have to install that package. I'll try to remove the dependency, as upstream bsnes did, for the next release.

**Comment by DerKoun** [comment]
I have removed libgtksourceview from the Linux build.
