### ISSUE TITLE
documentation [edit: how to compile]

### ISSUE THREAD

**Issue by neofeo** [DerKoun/bsnes-hd#94]
Hi, there is any documentation on how to compile it?, I need to compile it for arm linux, but standalone. it's missing ao.h and crashing, but probably its due a missing flag I guess.  

I compiled the original a long time ago, but also, lack of info.

**Comment by DerKoun** [comment]
https://github.com/DerKoun/bsnes-hd/blob/0fd18e0f5767284fd373aebd75b00b5bab0d44a9/.github/workflows/CI.yml#L57-L62
I hope the same process works for ARM.

If you can't compile with OpenMP, please see this patch apparently used in Lakka:
https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/bsnes_hd/patches/bsnes_hd-001-disable_openmp.patch

**Comment by neofeo** [comment]
add libasound2-dev

**Comment by neofeo** [comment]
mention : https://www.youtube.com/watch?v=s4WVE1ZcSXw

**Comment by DerKoun** [comment]
Good to see it working. No idea why you have to actively add ALSA.
Please let me know what exactly you did and I'll see where I can make a public note of it.

**Comment by neofeo** [comment]
no idea why, but alsa , that works by dafault its extremely slow. and yes, it asked alsa bc it fail to link if not.
