### ISSUE TITLE
RetroArch Shader Support

### ISSUE THREAD

**Issue by IndianaRoy** [DerKoun/bsnes-hd#95]
Hi, I've been trying to use shaders like xbrz and mmpx with the core but they do nothing while working without issue on the non HD bsnes

**Comment by DerKoun** [comment]
Fox pixel-art shaders you have to set the "scale" setting to "1x".
Otherwise the shaders get input that is already NN scaled and they can't work with that.

**Comment by IndianaRoy** [comment]
It's using the slang preset xbrz-freescale-multipass.slangp with scales at 1x

![retroarch 2021-06-26 17-34-24](https://user-images.githubusercontent.com/66286655/123527435-26924480-d6a5-11eb-97f8-8c6f4e4f6096.png)

**Comment by DerKoun** [comment]
I mean "scale" in the core settings

**Comment by DerKoun** [comment]
I'll close this, as there is no need for change.
I can explain further, but preferably on Discord.

**Comment by IndianaRoy** [comment]
Thanks
