### ISSUE TITLE
[Feature Request] Start in Fullscreen

### ISSUE THREAD

**Issue by tony971** [DerKoun/bsnes-hd#96]
Rather than toggling the fullscreen button after launching each ROM, it would be convenient to have a "start in fullscreen" option.

**Comment by DerKoun** [comment]
The command-line parameter is `--fullscreen`

**Comment by tony971** [comment]
Yes, that's what I use when going through a third-party launcher, but I was hoping to have native GUI support.

**Comment by DerKoun** [comment]
Fullscreen on startup requires a ROM to be specified. So you need to pass parameters anyway.

Please explain exactly what you want. I currently do not understand your use-case.

**Comment by tony971** [comment]
When selecting a game from the GUI, the game will boot windowed. I was hoping for a GUI option to boot games directly into fullscreen.
